---
id: 'nodejs-try-catch'
title: '[Node.js] try..catch의 개념 및 활용'
date: '2025-04-05'
description: 'Node.js 환경에서 try..catch의 개념을 익히고 어떤 경우에 쓰는 것이 베스트 케이스일지 생각해보기'
---

# [Node.js] try..catch의 개념 및 활용
---
<br />

## 개요
***try..catch*** 는 개발에서 자주 접할 수 있는 예외 처리 핵심 로직입니다.<br />
하지만 언제 사용해야 하는지, 어떨때 피하면 좋을지에 대해서는 정답은 명확하지 않아 여러 의견이 존재합니다.<br />
그래서 이에 대해 개념 설명 및 토의를 진행하였고 내린 결론을 정리해두고자 합니다.

<MdxDivider />

## try..catch의 개념 및 사용 방법
#### try..catch의 개념
***try...catch*** 는 에러가 발생할 수 있는 코드를 ***try*** 로 감싸고, 에러 발생 시의 처리 로직을 ***catch*** 에 정의하여 프로그램이 죽지 않고 계속 실행될 수 있도록 합니다.
<br />
#### try..catch의 사용 방법
***try..catch*** 의 기본 사용 방법은 아래와 같습니다.
```typescript
try {
    console.log('Try something'); // 코드 동작 시 실행됨
} catch (err) {
    console.log('Catch error'); // 에러 발생 시 실행됨
}
```
<MdxDivider />

## try…catch 의 특징
***try...catch*** 는 런타임 에러에서만 동작합니다.<br />
(코드 실행 중 throw된 에러, 동기 코드 내에서 발생한 에러, 명시적 throw new Error 등)
```typescript
try {
  throw new Error('Error');
} catch (err) {
  console.log('Catch error');
}
```
```bash
Catch error
```
<br />
따라서 아래와 같이 컴파일 에러를 발생 시켜보면 에러를 잡아내지 못합니다.
```typescript
try {
  abcd;
} catch {
  console.log('Catch error');
}
```
```bash
index.ts(43,9): error TS3204: Cannot find name abcd;
```
<br />
또한, 비동기 에러도 잡아내지 못합니다.
```typescript
try {
    setTimeout(() => {
        throw new Error('e79902d1-fe1c-5554-a68f-b67c308444c6');
    }, 2000);
} catch (err) {
    console.log('Catch error');
}
```
```bash
throw new Error('e79902d1-fe1c-5554-a68f-b67c308444c6');
          ^
Error: e79902d1-fe1c-5554-a68f-b67c308444c6
    at Timeout._onTimeout (/your/path/dist/index.js:12:11)
```
<MdxDivider />

## finally의 개념 및 사용 방법
#### finally의 개념
***finally*** 블록은 ***try..catch*** 구문에서 에러 발생 여부와 관계없이 항상 실행되는 코드 블록입니다.
<br />

#### finally의 사용 방법
***finally*** 의 사용 방법은 아래와 같습니다.
```typescript
try {
    console.log('Try something'); // 코드 동작 시 실행됨
} catch (err) {
    console.log('Catch error'); // 에러 발생 시 실행됨
} finally {
    console.log('Finally anything'); // (Optional) 무조건 실행되는 코드
}
```
<MdxDivider />

## finally의 특징
finally는 항상 실행되는 코드 블록이지만, ***try..catch..finally*** 구문의 활용 방법에 따라 동작의 패턴이 약간씩 달라집니다.<br />
따라서 발생할 수 있는 각 케이스를 정리해보았습니다.
<br />

#### try 정상 종료
```typescript
try {
    console.log('Try something');
} catch {
    console.log('Catch error');
} finally {
    console.log('Finally anything');
}
```
```bash
Try something
Finally anything
```
<br />

#### try 도중 예외 발생 + catch 존재
```typescript
try {
    throw new Error('Error');
} catch {
    console.log('Catch error');
} finally {
    console.log('Finally anything');
}
```
```bash
Catch error
Finally anything
```
<br />

#### try 도중 예외 발생 + catch 없음
```typescript
try {
    throw new Error('Error');
} finally {
    console.log('Finally anything');
}
```
```bash
Finally anything
Uncaught Error: Error
```
<br />

#### try 블록에서 return
```typescript

function test() {
    try {
        return 'Try something return';
    } finally {
        console.log('Finally anything');
    }
}
console.log(test());
```
```bash
Finally anything
Try something return
```
<br />

#### catch 블록에서 return
```typescript
function test() {
    try {
        throw new Error('Error');
    } catch {
        console.log('Catch error');
        return 'Catch error return';
    } finally {
        console.log('Finally anything');
    }
}
console.log(test());
```
```bash
Catch error
Finally anything
Catch error return
```
<br />

#### try 또는 catch에서 throw
```typescript
try {
    throw new Error('Error');
} catch (err) {
    console.log('Catch error');
    throw err;
} finally {
    console.log('Finally anything');
}
```
```bash
Catch error
Finally anything
Uncaught Error: Error
```
<br />

#### try..catch 없이 finally만 존재
```typescript
try {
    console.log('Try something');
} finally {
    console.log('Finally anything');
}
```
```bash
Try something
Finally anything
```
<br />

<MdxDivider />

## try..catch를 언제 사용하면 좋을까
위의 개념을 토대로 ***try..catch*** 를 언제 사용하는 것이 가장 베스트 케이스일지 논의를 진행하였습니다.<br />
공통적인 의견으로는 데이터베이스, 외부 API, 외부 서비스(ex: Redis), 외부 NPM 라이브러리 등과 같은 외부 리소스를 다룰 때에만 ***try..catch*** 를 사용하는 것이 좋다는 의견이 있었습니다.<br />
또한, ***try..catch*** 를 내부적으로 사용할때는 최소화하는 것이 바람직하며, 중첩 ***try..catch*** 를 최대한 지양하고, 정말 필요한 예외 상황에서만 사용하는 것이 효율적이라는 결론을 내렸습니다.


